### ISSUE TITLE
How to handle struct defaults

### ISSUE THREAD

**Issue by endersstocker** [Avocado-Living/elixir_style_guide#16]
The [`#nil-struct-field-defaults`](https://github.com/Avocado-Living/elixir_style_guide/blob/master/README.md#nil-struct-field-defaults) rule states:
>Use a list of atoms for struct fields that default to nil, followed by the other keywords.

While it’s helpful to have a rule for `defstruct`, this doesn’t seem like the right one. While `[:foo, :bar, baz: 42]` is understood by the compiler, the representation given by the **Inspect** protocol is the primitive one: `[:foo, :bar, {:baz, 42}]`. This is in contrast to `[{:foo, 1}, {:bar, 2}]` which is represented by **Inspect** as `[foo: 1, bar: 2]` or `[97, 98, 99]` which is represented as `'abc'`. The syntactic sugar that allows `[:foo, :bar, baz: 42]` to be evaluated belies the fact that this is a custom, compound data structure that _looks_ like a keyword list but is not in fact a keyword list. To make matters worse, the data structure has the same shape as an Erlang proplist, which has very different semantics.

More importantly, this is a very inflexible syntax. If I want to give a field a non-nil default value in the struct, I have to relocate it to the second section of the list. If I want to switch a default value to `nil`, I have to relocate it to the first section.

I can see three superior alternatives:

1. Always provide `defstruct` with a keyword list
2. If all defaults are `nil`, provide a list of atoms, otherwise use a keyword list
3. Provide a mixed list of atoms and 2-tuples

All three of these approaches preserve the ordering of fields in the `defstruct` call, addressing the syntactic rigidity of the current rule.

Number one makes changes the cleanest—you just replace the value in the keyword list. However, it’s not uncommon for a struct not to provide defaults; in these situations readability is hindered by nil-noise.

Number two only makes changes messy when converting between a struct with defaults and one without. Whether the struct provides defaults or not, the call is in its most readable format.

Number three makes changes nearly as clean as number one—you wrap the atom in a tuple to add a default, pull it out to remove the default. Unlike number one, structs without defaults are put in their most readable form. For structs with defaults however, this is a custom, compound data structure that future readers may find difficult to grok. Like the current solution, this structure has the problem of sharing its shape but not its semantics with a proplist.

What do you guys think? Do you prefer one of the given solutions? Can you offer an even better solution?

**Comment by endersstocker** [comment]
Currently
----------

No defaults:
```elixir
defmodule Person do
  defstruct [:dob, :favorite_color, :name, :nickname]
end
```

Defaults:
```elixir
defmodule Person do
  defstruct [:favorite_color, :nickname, dob: ~D[1970-01-01], name: "Joe Bloggs"]
end
```

Adding the first default:
<img width="633" alt="current-a" src="https://user-images.githubusercontent.com/2033828/52490452-c3b2b800-2b92-11e9-863f-fe2e78b8948b.png">


Adding another default:
<img width="633" alt="current-b" src="https://user-images.githubusercontent.com/2033828/52490463-c9a89900-2b92-11e9-9657-90ebb5e3f969.png">



Solution 1
----------

No defaults:
```elixir
defmodule Person do
  defstruct dob: nil, favorite_color: nil, name: nil, nickname: nil
end
```

Defaults:
```elixir
defmodule Person do
  defstruct dob: ~D[1970-01-01], favorite_color: nil, name: "Joe Bloggs", nickname: nil
end
```

Adding the first default:
<img width="633" alt="1-a" src="https://user-images.githubusercontent.com/2033828/52490476-cf9e7a00-2b92-11e9-88e8-3e3263889b72.png">


Adding another default:
<img width="633" alt="1-b" src="https://user-images.githubusercontent.com/2033828/52490481-d4632e00-2b92-11e9-9dc3-039a1a16ccb7.png">



Solution 2
----------

No defaults:
```elixir
defmodule Person do
  defstruct [:dob, :favorite_color, :name, :nickname]
end
```

Defaults:
```elixir
defmodule Person do
  defstruct dob: ~D[1970-01-01], favorite_color: nil, name: "Joe Bloggs", nickname: nil
end
```

Adding the first default:
<img width="633" alt="2-a" src="https://user-images.githubusercontent.com/2033828/52490503-da590f00-2b92-11e9-9092-2a35945ddb52.png">


Adding another default:
<img width="633" alt="2-b" src="https://user-images.githubusercontent.com/2033828/52490507-ddec9600-2b92-11e9-90d7-6771dbc7445f.png">



Solution 3
----------

No defaults:
```elixir
defmodule Person do
  defstruct [:dob, :favorite_color, :name, :nickname]
end
```

Defaults:
```elixir
defmodule Person do
  defstruct [{:dob, ~D[1970-01-01]}, :favorite_color, {:name, "Joe Bloggs"}, :nickname]
end
```

Adding the first default:
<img width="633" alt="3-a" src="https://user-images.githubusercontent.com/2033828/52490518-e6dd6780-2b92-11e9-9025-60598ef2249c.png">


Adding another default:
<img width="633" alt="3-b" src="https://user-images.githubusercontent.com/2033828/52490532-f0ff6600-2b92-11e9-87cf-11859f5287d3.png">

**Comment by endersstocker** [comment]
Things to consider:
1. How readable is the solution when there are no defaults?
2. How readable is the solution when there are defaults?
3. How clean is it to add another default?
4. How clean is it to switch between a struct with defaults and one without?

I consider the fourth least important since it comes into play infrequently.

**Comment by endersstocker** [comment]
## Regarding proplists
The structure
```elixir
[:favorite_color, :nickname, dob: ~D[1970-01-01], name: "Joe Bloggs"]
```
as a proplist would equate to
```elixir
[favorite_color: false, nickname: false, dob: ~D[1970-01-01], name: "Joe Bloggs"]
```

but as the fields for a struct would equate to
```elixir
[favorite_color: nil, nickname: nil, dob: ~D[1970-01-01], name: "Joe Bloggs"]
```

**Comment by acropoiesis** [comment]
Thanks Bryan. I would say Solution 1 works best for me. I'm fine with some nil-noise, as it gets rid of [ ]-noise. I can also see Solution 2 as an option if others prefer.

**Comment by poops** [comment]
Despite the downsides, I'm not against the current solution because I feel that it's more readable w/ or w/o defaults, which nails 1 & 2. I know it's not as clean to change them, but those changes will happen less frequently than reading them, so 3 & 4 are less important to me.

If the overall consensus is to change though, I think my vote would be for either Solution 2 or 3.

**Comment by endersstocker** [comment]
I’ll close this for now. If others see it as an issue down the road, we can re-open.
