### ISSUE TITLE
Style guide changes

### ISSUE THREAD

**Issue by poops** [Avocado-Living/elixir_style_guide#9]
Wanted to start discussions on a few items before opening PRs

1. [If you have more than one multiline `def`, do not use single-line `def`s](https://github.com/Avocado-Living/elixir_style_guide#multiple-function-defs)
I don't love this one because it could mean refactoring multiple functions when adding a new one. It also contradicts the example for [Run single-line `def`s that match for the same function together, but separate multiline `def`s with a blank line](https://github.com/Avocado-Living/elixir_style_guide#single-line-defs), which I think is how we should handle these.

2. [End each file with a newline](https://github.com/Avocado-Living/elixir_style_guide#newline-eof) contradicts [Avoid trailing whitespace](https://github.com/Avocado-Living/elixir_style_guide#trailing-whitespace)
Also Avocom currently has trailing newlines removed.

3. [If a struct definition spans multiple lines, put each element on its own line, keeping the elements aligned](https://github.com/Avocado-Living/elixir_style_guide#multiline-structs)
I personally dislike multiple indents to try to line things up. I'd prefer handling this situation like the example below it

If a multiline struct requires brackets, format it as a multiline list:

```elixir
  defstruct [
    :name,
    params: [],
    active: true
  ]
```

Everyone want to weigh in on these 3 items?

**Comment by andrewvy** [comment]
1. Seems good to me! I like keeping single-line defs together, but I don't like bunching up multi-line defs up against each other.

2. Newlines at the end of the file kinda irks me, I like following trailing whitespace should always be removed + superfluous newlines.

3. I think we should always use brackets, personally! (I also like always using parens, but that's another topic. :smile:)

**Comment by poops** [comment]
I'm also a fan of always using parens for function calls (but not for 0 arg definitions)

**Comment by endersstocker** [comment]
@andrewvy 2 is a POSIX requirement. If you use emacs or vim in default configuration, they put them in and hide them.

**Comment by endersstocker** [comment]
1. I agree. Let’s ditch that rule.
2. This one is a POSIX requirement. If you use emacs or vim in default configuration, they’re there, your editor just hides them. If you commit a file without an end-of-file newline, git will [complain](https://user-images.githubusercontent.com/2033828/51406218-79579180-1b26-11e9-9665-af0f114aa037.png).

3. The formatter actually enforces this one. We can just take out that rule and let the formatter handle it.

**Comment by endersstocker** [comment]
@poops 
1. I agree. Let’s ditch that rule.
2. This one is a POSIX requirement. If you use emacs or vim in default configuration, they’re there, your editor just hides them. If you commit a file without an end-of-file newline, git will [complain](https://user-images.githubusercontent.com/2033828/51406218-79579180-1b26-11e9-9665-af0f114aa037.png).
3. The formatter actually enforces this one. We can just take out that rule and let the formatter handle it.

**Comment by poops** [comment]
>   This one is a [POSIX requirement](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).  If you use emacs or vim in default configuration, they’re there, your editor just hides them.

Ah nice ok. I thought vim was stripping on save. Didn't realize it was hiding it.
